### ISSUE TITLE
Database undefined

### ISSUE THREAD

**Issue by ecj2** [ecj2/kaku#23]
When being redirected to the 404 page from either a post or a page in the 1.1 branch, the following error occurs:

```
2016/06/05 12:10:37 [error] 20577#20577: *1 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: Database in /home/eric/Documents/Servers/Web/kaku_1.1/core/classes/output.php on line 51
PHP message: PHP Fatal error:  Uncaught Error: Call to a member function getHandle() on null in /home/eric/Documents/Servers/Web/kaku_1.1/core/classes/output.php:51
Stack trace:
#0 /home/eric/Documents/Servers/Web/kaku_1.1/core/classes/output.php(233): Output->replaceTags()
#1 [internal function]: Output->replaceBufferContents('<!DOCTYPE html>...', 9)
#2 {main}
  thrown in /home/eric/Documents/Servers/Web/kaku_1.1/core/classes/output.php on line 51" while reading response header from upstream, client: 127.0.0.1, server: , request: "GET /kaku_1.1/post/welme+to+kaku HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.0-fpm.sock:", host: "127.0.0.1"
2016/06/05 12:10:37 [error] 20577#20577: *1 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: Database in /home/eric/Documents/Servers/Web/kaku_1.1/core/classes/output.php on line 51
PHP message: PHP Fatal error:  Uncaught Error: Call to a member function getHandle() on null in /home/eric/Documents/Servers/Web/kaku_1.1/core/classes/output.php:51
Stack trace:
#0 /home/eric/Documents/Servers/Web/kaku_1.1/core/classes/output.php(233): Output->replaceTags()
#1 [internal function]: Output->replaceBufferContents('', 9)
#2 {main}
  thrown in /home/eric/Documents/Servers/Web/kaku_1.1/core/classes/output.php on line 51" while reading response header from upstream, client: 127.0.0.1, server: , request: "GET /kaku_1.1/error?code=404 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.0-fpm.sock:", host: "127.0.0.1"

```

**Comment by ecj2** [comment]
This appears to happen every time header() is used to move to another file.
